# Generated by Django 2.2 on 2020-02-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200129_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
